// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_pokedex/test/pokemon_details_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:flutter_pokedex/src/data/providers/captured_hive.dart' as _i3;
import 'package:flutter_pokedex/src/domain/models/hive_adapters/hive_pokemon.dart'
    as _i5;
import 'package:hive_flutter/hive_flutter.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeHiveInterface_0 extends _i1.SmartFake implements _i2.HiveInterface {
  _FakeHiveInterface_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBoxBase_1<E> extends _i1.SmartFake implements _i2.BoxBase<E> {
  _FakeBoxBase_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CapturedHive].
///
/// See the documentation for Mockito's code generation for more information.
class MockCapturedHive extends _i1.Mock implements _i3.CapturedHive {
  @override
  String get name => (super.noSuchMethod(
        Invocation.getter(#name),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
        returnValueForMissingStub: _i4.dummyValue<String>(
          this,
          Invocation.getter(#name),
        ),
      ) as String);

  @override
  bool get lazy => (super.noSuchMethod(
        Invocation.getter(#lazy),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.KeyComparator get keyComparator => (super.noSuchMethod(
        Invocation.getter(#keyComparator),
        returnValue: (
          dynamic key1,
          dynamic key2,
        ) =>
            0,
        returnValueForMissingStub: (
          dynamic key1,
          dynamic key2,
        ) =>
            0,
      ) as _i2.KeyComparator);

  @override
  _i2.CompactionStrategy get compactionStrategy => (super.noSuchMethod(
        Invocation.getter(#compactionStrategy),
        returnValue: (
          int entries,
          int deletedEntries,
        ) =>
            false,
        returnValueForMissingStub: (
          int entries,
          int deletedEntries,
        ) =>
            false,
      ) as _i2.CompactionStrategy);

  @override
  bool get crashRecovery => (super.noSuchMethod(
        Invocation.getter(#crashRecovery),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.HiveInterface get hive => (super.noSuchMethod(
        Invocation.getter(#hive),
        returnValue: _FakeHiveInterface_0(
          this,
          Invocation.getter(#hive),
        ),
        returnValueForMissingStub: _FakeHiveInterface_0(
          this,
          Invocation.getter(#hive),
        ),
      ) as _i2.HiveInterface);

  @override
  set hive(_i2.HiveInterface? _hive) => super.noSuchMethod(
        Invocation.setter(
          #hive,
          _hive,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i2.BoxBase<_i5.HivePokemon> get box => (super.noSuchMethod(
        Invocation.getter(#box),
        returnValue: _FakeBoxBase_1<_i5.HivePokemon>(
          this,
          Invocation.getter(#box),
        ),
        returnValueForMissingStub: _FakeBoxBase_1<_i5.HivePokemon>(
          this,
          Invocation.getter(#box),
        ),
      ) as _i2.BoxBase<_i5.HivePokemon>);

  @override
  set box(_i2.BoxBase<_i5.HivePokemon>? _box) => super.noSuchMethod(
        Invocation.setter(
          #box,
          _box,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<bool> get isOpen => (super.noSuchMethod(
        Invocation.getter(#isOpen),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<String?> get path => (super.noSuchMethod(
        Invocation.getter(#path),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<Iterable<dynamic>> get keys => (super.noSuchMethod(
        Invocation.getter(#keys),
        returnValue: _i6.Future<Iterable<dynamic>>.value(<dynamic>[]),
        returnValueForMissingStub:
            _i6.Future<Iterable<dynamic>>.value(<dynamic>[]),
      ) as _i6.Future<Iterable<dynamic>>);

  @override
  _i6.Future<int> get length => (super.noSuchMethod(
        Invocation.getter(#length),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<bool> get isEmpty => (super.noSuchMethod(
        Invocation.getter(#isEmpty),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<bool> get isNotEmpty => (super.noSuchMethod(
        Invocation.getter(#isNotEmpty),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<Iterable<_i5.HivePokemon>?> get values => (super.noSuchMethod(
        Invocation.getter(#values),
        returnValue: _i6.Future<Iterable<_i5.HivePokemon>?>.value(),
        returnValueForMissingStub:
            _i6.Future<Iterable<_i5.HivePokemon>?>.value(),
      ) as _i6.Future<Iterable<_i5.HivePokemon>?>);

  @override
  _i6.Future<_i2.BoxBase<_i5.HivePokemon>> init([_i2.HiveInterface? hive]) =>
      (super.noSuchMethod(
        Invocation.method(
          #init,
          [hive],
        ),
        returnValue: _i6.Future<_i2.BoxBase<_i5.HivePokemon>>.value(
            _FakeBoxBase_1<_i5.HivePokemon>(
          this,
          Invocation.method(
            #init,
            [hive],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i2.BoxBase<_i5.HivePokemon>>.value(
                _FakeBoxBase_1<_i5.HivePokemon>(
          this,
          Invocation.method(
            #init,
            [hive],
          ),
        )),
      ) as _i6.Future<_i2.BoxBase<_i5.HivePokemon>>);

  @override
  _i6.Future<void> reopen() => (super.noSuchMethod(
        Invocation.method(
          #reopen,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Iterable<_i5.HivePokemon>?> valuesBetween({
    dynamic startKey,
    dynamic endKey,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #valuesBetween,
          [],
          {
            #startKey: startKey,
            #endKey: endKey,
          },
        ),
        returnValue: _i6.Future<Iterable<_i5.HivePokemon>?>.value(),
        returnValueForMissingStub:
            _i6.Future<Iterable<_i5.HivePokemon>?>.value(),
      ) as _i6.Future<Iterable<_i5.HivePokemon>?>);

  @override
  _i6.Future<_i5.HivePokemon?> get(
    dynamic key, {
    _i5.HivePokemon? defaultValue,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [key],
          {#defaultValue: defaultValue},
        ),
        returnValue: _i6.Future<_i5.HivePokemon?>.value(),
        returnValueForMissingStub: _i6.Future<_i5.HivePokemon?>.value(),
      ) as _i6.Future<_i5.HivePokemon?>);

  @override
  _i6.Future<_i5.HivePokemon?> getAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #getAt,
          [index],
        ),
        returnValue: _i6.Future<_i5.HivePokemon?>.value(),
        returnValueForMissingStub: _i6.Future<_i5.HivePokemon?>.value(),
      ) as _i6.Future<_i5.HivePokemon?>);

  @override
  _i6.Stream<_i2.BoxEvent> watch({dynamic key}) => (super.noSuchMethod(
        Invocation.method(
          #watch,
          [],
          {#key: key},
        ),
        returnValue: _i6.Stream<_i2.BoxEvent>.empty(),
        returnValueForMissingStub: _i6.Stream<_i2.BoxEvent>.empty(),
      ) as _i6.Stream<_i2.BoxEvent>);

  @override
  _i6.Future<bool> containsKey(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #containsKey,
          [key],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<void> put(
    dynamic key,
    _i5.HivePokemon? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> putAt(
    int? index,
    _i5.HivePokemon? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAt,
          [
            index,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> putAll(Map<dynamic, _i5.HivePokemon>? entries) =>
      (super.noSuchMethod(
        Invocation.method(
          #putAll,
          [entries],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> add(_i5.HivePokemon? value) => (super.noSuchMethod(
        Invocation.method(
          #add,
          [value],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<Iterable<int>> addAll(Iterable<_i5.HivePokemon>? values) =>
      (super.noSuchMethod(
        Invocation.method(
          #addAll,
          [values],
        ),
        returnValue: _i6.Future<Iterable<int>>.value(<int>[]),
        returnValueForMissingStub: _i6.Future<Iterable<int>>.value(<int>[]),
      ) as _i6.Future<Iterable<int>>);

  @override
  _i6.Future<void> delete(dynamic key) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAt(int? index) => (super.noSuchMethod(
        Invocation.method(
          #deleteAt,
          [index],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> deleteAll(Iterable<dynamic>? keys) => (super.noSuchMethod(
        Invocation.method(
          #deleteAll,
          [keys],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> compact() => (super.noSuchMethod(
        Invocation.method(
          #compact,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<int> clear() => (super.noSuchMethod(
        Invocation.method(
          #clear,
          [],
        ),
        returnValue: _i6.Future<int>.value(0),
        returnValueForMissingStub: _i6.Future<int>.value(0),
      ) as _i6.Future<int>);

  @override
  _i6.Future<void> deleteFromDisk() => (super.noSuchMethod(
        Invocation.method(
          #deleteFromDisk,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> flush() => (super.noSuchMethod(
        Invocation.method(
          #flush,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<Map<dynamic, _i5.HivePokemon>?> toMap() => (super.noSuchMethod(
        Invocation.method(
          #toMap,
          [],
        ),
        returnValue: _i6.Future<Map<dynamic, _i5.HivePokemon>?>.value(),
        returnValueForMissingStub:
            _i6.Future<Map<dynamic, _i5.HivePokemon>?>.value(),
      ) as _i6.Future<Map<dynamic, _i5.HivePokemon>?>);

  @override
  _i6.Future<void> close() => (super.noSuchMethod(
        Invocation.method(
          #close,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
