name: flutter_pokedex
description: "Code challenge para Flutter Developers."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  theme_tailor_annotation: ^3.0.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  theme_tailor: ^3.0.1

flutter:
  uses-material-design: true
