name: flutter_pokedex
description: "Code challenge para Flutter Developers."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  bloc: ^8.1.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  injectable: ^2.3.2
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  retrofit: ^4.1.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.4.7
  injectable_generator: ^2.4.1
  json_serializable: ^6.7.1
  retrofit_generator: ^8.1.0

flutter:
  uses-material-design: true
